<template>
	<v-container fluid>
		<h1 class="my-3">Introduction</h1>

		<v-divider></v-divider>
		<v-layout row wrap id="environment"></v-layout>
		<v-flex xs8><h2 class="my-2">Environment</h2></v-flex>
		<p>
			The application environment consists of :
			<ul>
				<li><b><a @click="$router.push({name:'Blocks'})">Blocks</a></b>, the building block of your program, which can be connected to other blocks</li>
				<li><b><a @click="$router.push({name:'Toolbox'})">Toolbox</a></b>, which houses the available blocks.</li>
				<li><b><a @click="$router.push({name:'Workspace'})">Workspace</a></b>, where the blocks are built into a program</li>
				<li><b><a @click="$router.push({name:'Console'})">Console</a></b>, where the code outputs generated by the blocks are displayed</li>
			</ul>
		</p>
		<p>
			<i>Note : The application must be hosted on a Raspberry Pi to make full use of it's features.</i>
		</p>
	</v-flex>
</v-layout>
<v-divider></v-divider>
<v-layout row wrap id="features">
	<v-flex xs8><h2 class="my-2">Features</h2></v-flex>
	<v-flex xs8><p> The application comes with a number of features :
		<ul>
			<li>Access to GPIO pins of a Raspberry Pi.</li>
			<li>Create programs to control these pins using Blocks</li>
			<li>View the code generated by your blocks.</li>
			<li>View the output generated by your blocks.</li>
			<li>View the active GPIO components created by your program.</li>
			<li>Instructions for an introductory <b><a @click="$router.push({name:'Projects'})">project</a></b>.</li>
			<li>Real Time Collaboration. An individual workspace can be accessed by using the URL provided in the <b><a @click="openSettings()">Settings</a></b>.</li>

		</ul>
	</p> </v-flex>
</v-layout>
<v-divider></v-divider>
<v-layout row wrap id="features">
	<v-flex xs8><h2 class="my-2">Requirements</h2></v-flex>
	<v-flex xs8><p> The application has a few requirements to use :
		<ul>

			<li>A Raspberry Pi.</li>
			<li>Access to a web browser.</li>
			<li>A local network for collaboration and access from an external computer.</li>
			<li>One or more of the following Raspberry Pi components : <ul>
				<li>LED</li>
				<li>Button</li>
				<li>RGB LED</li>
			</ul></li>


		</ul>
		<li>No previous coding experience is required.</li>
	</p> </v-flex>
</v-layout>
</v-container>
</template>
<script>
	export default{
		name:'Introduction',
		data(){
			return {

			}
		},
		methods:{
			openSettings(){
				document.getElementById('settings-btn').click()
			},
			getComponentImg(type){
				var img = require("../../assets/staticimg/"+type+".png")
				return img
			}
		}
	}
</script>

<style>
</style>